// <auto-generated />
namespace marketplace1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class phase2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phase2));
        
        string IMigrationMetadata.Id
        {
            get { return "202407271600058_phase2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
